import type { Category, ClinicCardData } from "./types";

export const CATEGORIES: Category[] = [
  { slug: "botox", label: "โบท็อกซ์", icon: "💉" },
  { slug: "laser", label: "เลเซอร์", icon: "✨" },
  { slug: "nose", label: "จมูก", icon: "👃" },
  { slug: "eye", label: "ตา 2 ชั้น", icon: "👁️" },
  { slug: "dental", label: "ทันตกรรม", icon: "🦷" },
  { slug: "acne", label: "รักษาสิว", icon: "🧴" },
  { slug: "slimming", label: "สลายไขมัน", icon: "⚖️" },
  { slug: "treatment", label: "ทรีตเมนต์", icon: "💆" },
];

export const MOCK_CLINICS: ClinicCardData[] = [
  {
    id: "glow-up-siam",
    name: "Glow Up Clinic สยาม",
    tier: "premier",
    rating: 4.9,
    reviewCount: 234,
    priceFrom: 4990,
    distanceKm: 0.4,
    district: "BTS สยาม",
    tags: ["โบท็อกซ์", "ฟิลเลอร์"],
    badges: [{ kind: "hot" }, { kind: "installment", months: 0 }, { kind: "book-today" }],
    imageGradient: "linear-gradient(135deg, #2a1538 0%, #4a1a55 50%, #1d0d28 100%)",
  },
  {
    id: "clear-skin",
    name: "Clear Skin Clinic",
    tier: "premier",
    rating: 4.8,
    reviewCount: 189,
    priceFrom: 3500,
    distanceKm: 1.2,
    district: "พระราม 9",
    tags: ["เลเซอร์", "คอร์ส 3 ครั้ง"],
    badges: [],
    imageGradient: "linear-gradient(135deg, #0d2438 0%, #1a3a55 50%, #0a1a2a 100%)",
  },
  {
    id: "perfect-nose",
    name: "Perfect Nose Center",
    tier: "verified",
    rating: 4.7,
    reviewCount: 92,
    priceFrom: 30000,
    distanceKm: 2.1,
    district: "ทองหล่อ",
    tags: ["ศัลยกรรม", "ผ่อน 10 เดือน"],
    badges: [{ kind: "installment", months: 10 }],
    imageGradient: "linear-gradient(135deg, #1a2818 0%, #2d3a25 50%, #0f1a0d 100%)",
  },
  {
    id: "beauty-ladprao",
    name: "Beauty Clinic ลาดพร้าว",
    tier: "free",
    rating: 4.5,
    reviewCount: 41,
    priceFrom: 2000,
    distanceKm: 3.8,
    district: "ลาดพร้าว",
    tags: ["ทรีตเมนต์"],
    badges: [],
    imageGradient: "linear-gradient(135deg, #1a1a1a 0%, #262626 50%, #0d0d0d 100%)",
  },
];
